apiVersion: v1
kind: Service
metadata:
  name: api-server-service
spec:
  selector:
    app: api-server
  ports:
  - name: http
    port: 80
    targetPort: 8000
  type: LoadBalancer  # Expose to an external IP