apiVersion: v1
kind: Service
metadata:
  name: api-server-service
spec:
  selector:
    app: api-server
  ports:
    - protocol: TCP
      port: 80  # External port exposed to the world
      targetPort: 8000  # Port the container listens on
  type: LoadBalancer
