apiVersion: v1
kind: Service
metadata:
  name: inference-service
spec:
  selector:
    app: inference
  ports:
  - name: http
    port: 80
    targetPort: 8000  # Replace with the port your application listens to
